[package]
name = "exploded"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = "0.19"
web-sys = "0.3"
js-sys = "0.3"
wasm-bindgen = "0.2"
rand = "0.8.5"

[dependencies.getrandom]
version = "0.2"
features = ["js"]
