[package]
name = "exploded-server"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
actix = "0.13"
actix-web = "4"
actix-web-actors = "4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
